name: Compare Func
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell')}}
          STARTS_WITH_FUNC: ${{startsWith('Hello', 'He')}}
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo')}}
          RESULT_FALSE_ENDS_WITH_FUNC: ${{ endsWith('Hello', 'le')}}
