name: Hello World
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - uses: actions/checkout@v4
      - run: echo "::debug::hello_world"
      - run: |
          set -x
          date
          hostname
      - run: echo "::error::error-message"
      - run: echo "::warning::error-message"
      - run: echo "::notice::error-message"
      - run: | # markdown
          echo "## Example title :rocket:" >> "${GITHUB_STEP_SUMMARY}"
          echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
          echo "- second line" >> "${GITHUB_STEP_SUMMARY}"

